### ISSUE TITLE
after minimize several times app event not work 

### ISSUE THREAD

**Issue by tsonevn** [nativescript-vue/nativescript-vue#196]
_From @A1Gard on April 24, 2018 5:48_

I was compile a new app with native-vue-template by this code:
`
 tns create fireApp --template nativescript-vue-template`

and I try to compile and install in my phone.

but after after minimize several times app event not work.

Problem is detect on **andriod** platform, I don't check on ios app.

```
$ tns --version
4.0.0
```
My phone is Nexus p6 and andriod 7.1.1.
Sdk comile is latest sdk install with last andriod studio version.

an here is video attached:

![ezgif-3-8755d4642d](https://user-images.githubusercontent.com/9222481/39168377-da9f6a6e-47a8-11e8-9cec-ac790d9e0156.gif)

_Copied from original issue: NativeScript/NativeScript#5730_

**Comment by A1Gard** [comment]
Hi @tsonevn 
Why issue moving here?
I'd use `tns` only  to compile and other actions.

What about the solution?

**Comment by rigor789** [comment]
It has been moved because it is specific to the nativescript-vue implementation. This is a somewhat known issue that I'm fixing currently. There is a `rc` release which should solve the problem, although more testing is needed. Can you try updating to `nativescript-vue@1.3.2-rc.4` and let me know how it goes?

**Comment by A1Gard** [comment]
@rigor789 I install the `nativescript-vue@1.3.2-rc.4` :
```
$ sudo npm install -g nativescript-vue@1.3.2-rc.4
[sudo] password for user: 
+ nativescript-vue@1.3.2-rc.4
added 1 package in 2.034s
```
but problem still exist  :sob: 
Problem when detect minimize with `[back button]`

**Comment by rigor789** [comment]
The `1.4.0-alpha.0` version should solve this, check https://github.com/nativescript-vue/nativescript-vue/issues/239#issuecomment-394780299 for upgrade instructions.
