### ISSUE TITLE
endless render loop

### ISSUE THREAD

**Issue by farfromrefug** [nativescript-vue/nativescript-vue#447]
### Version
2.0.2

### Reproduction link
[https://github.com/farfromrefug/vue_ts_template](https://github.com/farfromrefug/vue_ts_template)
### Platform and OS info
all

### Steps to reproduce
change ```importHelpers``` to false in the tsconfig file and run.

### What is expected?
to run

### What is actually happening?
endless render loop

---
related to this issue https://github.com/NativeScript/android-runtime/issues/1179

**Comment by jjstrat3** [comment]
@farfromrefug Looks like the issue was solved for you based on what I read in the NativeScript issue you linked?  Perhaps you could close this now?

**Comment by farfromrefug** [comment]
Well not exactly. Still happening on iOS. I think we should keep this open until it's confirmed to be an issue with the ```ios-runtime```
